//----------------------------APP-------
export const APP_RELOAD_FROM_LOCAL_STORAGE = 'APP_RELOAD_FROM_LOCAL_STORAGE';
export const INIT_CONTAINER_APP_DID_MOUNT = 'INIT_CONTAINER_APP_DID_MOUNT';
export const APP_SCREEN_HEIGHT_LISTENNER = 'APP_SCREEN_HEIGHT_LISTENNER';
export const APP_FULL_SCREEN = 'APP_FULL_SCREEN';
export const APP_DELETE_MENU_ITEM = 'APP_DELETE_MENU_ITEM';
//----------------------------sidebar
export const SIDE_BAR_MENU_ITEM_TOGGLE = 'SIDE_BAR_MENU_ITEM_TOGGLE';
export const SIDE_BAR_MENU_SCROLL = 'SIDE_BAR_MENU_SCROLL';
export const SIDE_BAR_MINI_MENU_HOVER_MENU = 'SIDE_BAR_MINI_MENU_HOVER_MENU';
//----------------------------container
export const HEADER_TOGGLE = 'HEADER_TOGGLE';
//----------------------------container-tittle-menu
export const CONTAINER_TITTLE_MENU_SELECT_ACTIVE_CONTENT = 'CONTAINER_TITTLE_MENU_SELECT_ACTIVE_CONTENT';
export const CONTAINER_TITTLE_MENU_SET_LIMIT_AND_CURSOR = 'CONTAINER_TITTLE_MENU_SET_LIMIT_AND_CURSOR';
export const CONTAINER_TITTLE_MENU_SCROLL = 'CONTAINER_TITTLE_MENU_SCROLL';
export const CONTAINER_TITTLE_MENU_DELETE_ACTIVE_CONTENT = 'CONTAINER_TITTLE_MENU_DELETE_ACTIVE_CONTENT';
export const CONTAINER_TITTLE_MENU_CLOSE_OPTION = 'CONTAINER_TITTLE_MENU_CLOSE_OPTION';
export const CONTAINER_TITTLE_MENU_CLOSE_ALL_ITEM='CONTAINER_TITTLE_MENU_CLOSE_ALL_ITEM';
export const CONTAINER_TITTLE_MENU_CLOSE_OTHER_ITEM='CONTAINER_TITTLE_MENU_CLOSE_OTHER_ITEM';
export const CONTAINER_TITTLE_MENU_FORK_ACTIVE_ITEM ='CONTAINER_TITTLE_MENU_FORK_ACTIVE_ITEM';
//----------------------------content-setting
export const CONTENT_SETTING_INIT = 'CONTENT_SETTING_INIT';
export const CONTENT_SETTING_CHECK_RIGHT_ACTIVE_CONTAINER='CONTENT_SETTING_CHECK_RIGHT_ACTIVE_CONTAINER';
export const CONTENT_SETTING_CHANGE_SKIN='CONTENT_SETTING_CHANGE_SKIN';
export const CONTENT_SETTING_CHANGE_MENU='CONTENT_SETTING_CHANGE_MENU';
export const CONTENT_SETTING_SETTING_MENU_TOGGLE_TABLE_MENU_ITEM='CONTENT_SETTING_SETTING_MENU_TOGGLE_TABLE_MENU_ITEM';
export const CONTENT_SETTING_SETTING_MENU_TOGGLE_OFF_MENU_ITEM='CONTENT_SETTING_SETTING_MENU_TOGGLE_OFF_MENU_ITEM';
export const CONTENT_SETTING_SETTING_MENU_SELECT_TABLE_MENU_ITEM='CONTENT_SETTING_SETTING_MENU_SELECT_TABLE_MENU_ITEM';
//----------------------------menu-setting-option
export const MENU_SETTING_OPTION_MENU_DID_MOUNT = 'MENU_SETTING_OPTION_MENU_DID_MOUNT';
export const MENU_SETTING_OPTION_CHECK_IS_ROOT_MENU = 'MENU_SETTING_OPTION_CHECK_IS_ROOT_MENU';
export const MENU_SETTING_OPTION_ONCLICK_NEXT_STEP = 'MENU_SETTING_OPTION_ONCLICK_NEXT_STEP';
export const MENU_SETTING_OPTION_ONCLICK_CHANGE_STEP = 'MENU_SETTING_OPTION_ONCLICK_CHANGE_STEP';