//----------------------------APP-------
export const APP_USER_LOGIN = 'APP_USER_LOGIN';
export const APP_RELOAD_FROM_LOCAL_STORAGE = 'APP_RELOAD_FROM_LOCAL_STORAGE';
export const INIT_CONTAINER_APP_DID_MOUNT = 'INIT_CONTAINER_APP_DID_MOUNT';
export const APP_SCREEN_HEIGHT_LISTENNER = 'APP_SCREEN_HEIGHT_LISTENNER';
export const APP_FULL_SCREEN = 'APP_FULL_SCREEN';
export const APP_DELETE_MENU_ITEM = 'APP_DELETE_MENU_ITEM';
//piecemeal-components---------------------------------
//----------------------------shield-alert
export const SHIELD_ALERT_ON_OK_DELETE_ERROR_FLAG = 'SHIELD_ALERT_ON_OK_DELETE_ERROR_FLAG';
export const SHIELD_OK_ON_OK_DELETE_OK_FLAG = 'SHIELD_OK_ON_OK_DELETE_OK_FLAG';
export const SHIELD_BUTTON_GROUP_ROLE_AUTHORIZE_TOGGLE_STATUS = 'SHIELD_BUTTON_GROUP_ROLE_AUTHORIZE_TOGGLE_STATUS';
export const SHIELD_BUTTON_GROUP_ROLE_AUTHORIZE_BATCH_SELECT_ITEM = 'SHIELD_BUTTON_GROUP_ROLE_AUTHORIZE_BATCH_SELECT_ITEM';
//----------------------------button-group-role-authorize
export const BUTTON_GROUP_ROLE_AUTHORIZE_CLOSE = 'BUTTON_GROUP_ROLE_AUTHORIZE_CLOSE';
export const SHIELD_BUTTON_GROUP_ROLE_AUTHORIZE_INIT_ITEM = 'SHIELD_BUTTON_GROUP_ROLE_AUTHORIZE_INIT_ITEM';

//----------------------------shield-modify-search-group-config
export const MODIFY_SEARCH_GROUP_CONFIG_INIT_STATE = 'MODIFY_SEARCH_GROUP_CONFIG_INIT_STATE';
export const MODIFY_SEARCH_GROUP_CONFIG_SAVE_DATA_HAS_CREATED = 'MODIFY_SEARCH_GROUP_CONFIG_SAVE_DATA_HAS_CREATED';
//Components------------------------------------------------
//----------------------------sidebar
export const SIDE_BAR_MENU_ITEM_TOGGLE = 'SIDE_BAR_MENU_ITEM_TOGGLE';
export const SIDE_BAR_MENU_SCROLL = 'SIDE_BAR_MENU_SCROLL';
export const SIDE_BAR_MINI_MENU_HOVER_MENU = 'SIDE_BAR_MINI_MENU_HOVER_MENU';
//----------------------------container
export const HEADER_TOGGLE = 'HEADER_TOGGLE';
//----------------------------container-tittle-menu
export const CONTAINER_TITTLE_MENU_SELECT_ACTIVE_CONTENT = 'CONTAINER_TITTLE_MENU_SELECT_ACTIVE_CONTENT';
export const CONTAINER_TITTLE_MENU_SET_LIMIT_AND_CURSOR = 'CONTAINER_TITTLE_MENU_SET_LIMIT_AND_CURSOR';
export const CONTAINER_TITTLE_MENU_SCROLL = 'CONTAINER_TITTLE_MENU_SCROLL';
export const CONTAINER_TITTLE_MENU_DELETE_ACTIVE_CONTENT = 'CONTAINER_TITTLE_MENU_DELETE_ACTIVE_CONTENT';
export const CONTAINER_TITTLE_MENU_CLOSE_OPTION = 'CONTAINER_TITTLE_MENU_CLOSE_OPTION';
export const CONTAINER_TITTLE_MENU_CLOSE_ALL_ITEM='CONTAINER_TITTLE_MENU_CLOSE_ALL_ITEM';
export const CONTAINER_TITTLE_MENU_CLOSE_OTHER_ITEM='CONTAINER_TITTLE_MENU_CLOSE_OTHER_ITEM';
export const CONTAINER_TITTLE_MENU_FORK_ACTIVE_ITEM ='CONTAINER_TITTLE_MENU_FORK_ACTIVE_ITEM';
//----------------------------content-setting
export const CONTENT_SETTING_INIT = 'CONTENT_SETTING_INIT';
export const CONTENT_SETTING_QUICK_BUTTON_TABLE_TOGGLE = 'CONTENT_SETTING_QUICK_BUTTON_TABLE_TOGGLE';
export const CONTENT_SETTING_CHANGE_QUICK_BUTTON = 'CONTENT_SETTING_CHANGE_QUICK_BUTTON';
export const CONTENT_SETTING_SELECT_DATA_BABEL_ITEM = 'CONTENT_SETTING_SELECT_DATA_BABEL_ITEM';
export const CONTENT_SETTING_CHECK_RIGHT_ACTIVE_CONTAINER='CONTENT_SETTING_CHECK_RIGHT_ACTIVE_CONTAINER';
export const CONTENT_SETTING_CHANGE_SKIN='CONTENT_SETTING_CHANGE_SKIN';
export const CONTENT_SETTING_CHANGE_USER_INFO='CONTENT_SETTING_CHANGE_USER_INFO';
export const CONTENT_SETTING_CHANGE_MENU='CONTENT_SETTING_CHANGE_MENU';
export const CONTENT_SETTING_SETTING_MENU_TOGGLE_TABLE_MENU_ITEM='CONTENT_SETTING_SETTING_MENU_TOGGLE_TABLE_MENU_ITEM';
export const CONTENT_SETTING_SETTING_MENU_TOGGLE_OFF_MENU_ITEM='CONTENT_SETTING_SETTING_MENU_TOGGLE_OFF_MENU_ITEM';
export const CONTENT_SETTING_SETTING_MENU_SELECT_TABLE_MENU_ITEM='CONTENT_SETTING_SETTING_MENU_SELECT_TABLE_MENU_ITEM';
export const CONTENT_SETTING_SETTING_MENU_SEND_ERROR='CONTENT_SETTING_SETTING_MENU_SEND_ERROR';
export const CONTENT_SETTING_RESET_PASS_WORD='CONTENT_SETTING_RESET_PASS_WORD';
export const CONTENT_SETTING_SETTING_IS_OK='CONTENT_SETTING_SETTING_IS_OK';
//----------------------------menu-setting-option
export const MENU_SETTING_OPTION_MENU_DID_MOUNT = 'MENU_SETTING_OPTION_MENU_DID_MOUNT';
export const MENU_SETTING_OPTION_CHECK_IS_ROOT_MENU = 'MENU_SETTING_OPTION_CHECK_IS_ROOT_MENU';
export const MENU_SETTING_OPTION_ONCLICK_NEXT_STEP = 'MENU_SETTING_OPTION_ONCLICK_NEXT_STEP';
export const MENU_SETTING_OPTION_ONCLICK_CHANGE_STEP = 'MENU_SETTING_OPTION_ONCLICK_CHANGE_STEP';
export const MENU_SETTING_TOGGLE_ICON_SETTING = 'MENU_SETTING_TOGGLE_ICON_SETTING';
export const MENU_SETTING_CHANGE_MENU_DATA = 'MENU_SETTING_CHANGE_MENU_DATA';
export const MENU_SETTING_ADD_MENU_TO_SIDE_BAR = 'MENU_SETTING_ADD_MENU_TO_SIDE_BAR';
export const MENU_SETTING_GET_VIEW_POINT_CONFIG = 'MENU_SETTING_GET_VIEW_POINT_CONFIG';
export const MENU_SETTING_SEND_ERROR_MESSAGE = 'MENU_SETTING_SEND_ERROR_MESSAGE';
export const MENU_SETTING_RESET_ERROR = 'MENU_SETTING_RESET_ERROR';
export const MENU_SETTING_CHANGE_PREVIEW_STATUS = 'MENU_SETTING_CHANGE_PREVIEW_STATUS';
export const MENU_SETTING_ADD_MENU_FINISH = 'MENU_SETTING_ADD_MENU_FINISH';
export const MENU_SETTING_MODIFY_MENU_FINISH = 'MENU_SETTING_MODIFY_MENU_FINISH';
export const MENU_SETTING_CHANGE_BUTTON_CONFIG_PREVIEW_STATUS = 'MENU_SETTING_CHANGE_BUTTON_CONFIG_PREVIEW_STATUS';

//----------------------------normal-table
export const NORMAL_TABLE_INIT = 'NORMAL_TABLE_INIT';
export const NORMAL_TABLE_ON_CLICK_BUTTON = 'NORMAL_TABLE_ON_CLICK_BUTTON';
export const NORMAL_TABLE_CHECK_ON_ITEM = 'NORMAL_TABLE_CHECK_ON_ITEM';
export const NORMAL_TABLE_GET_DATA = 'NORMAL_TABLE_GET_DATA';
export const NORMAL_TABLE_SAVE_MODIFY_VIEW_DATA = 'NORMAL_TABLE_SAVE_MODIFY_VIEW_DATA';
export const NORMAL_TABLE_TOGGLE_ITEM = 'NORMAL_TABLE_TOGGLE_ITEM';
export const NORMAL_TABLE_SUBMIT_MODIFY_DATA = 'NORMAL_TABLE_SUBMIT_MODIFY_DATA';
export const NORMAL_TABLE_SUBMIT_DELETE_DATA = 'NORMAL_TABLE_SUBMIT_DELETE_DATA';
export const NORMAL_TABLE_SUBMIT_ADD_DATA = 'NORMAL_TABLE_SUBMIT_ADD_DATA';
export const NORMAL_TABLE_SUBMIT_TABLE_TOGGLE_OPTION = 'NORMAL_TABLE_SUBMIT_TABLE_TOGGLE_OPTION';
export const NORMAL_TABLE_BATCH_SELECT_ITEM = 'NORMAL_TABLE_BATCH_SELECT_ITEM';
export const NORMAL_TABLE_BATCH_OPTION_IS_OPEN = 'NORMAL_TABLE_BATCH_OPTION_IS_OPEN';
export const NORMAL_TABLE_TOGGLE_SEARCH_GROUP = 'NORMAL_TABLE_TOGGLE_SEARCH_GROUP';

